import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../models/college_model.dart';
import '../../../../core/services/firebase_service.dart';

class CollegeRepository {
  final FirebaseFirestore _firestore;

  CollegeRepository(this._firestore);

  /// Returns a stream of colleges.
  /// By default, it filters out deleted colleges.
  Stream<List<College>> getCollegesStream({bool showDeleted = false}) {
    Query query = _firestore.collection('colleges');
    
    if (!showDeleted) {
      query = query.where('isDeleted', isEqualTo: false);
    }

    // Sort by createdAt descending by default to show newest first
    query = query.orderBy('createdAt', descending: true);

    return query.snapshots().map((snapshot) {
      return snapshot.docs.map((doc) => College.fromFirestore(doc)).toList();
    });
  }

  /// Adds a new college to Firestore.
  /// Note: The ID is auto-generated by Firestore.
  Future<void> addCollege(College college) async {
    // We converting to map but removing the ID since Firestore generates it, 
    // or we can set the ID if the model already has one (which is rare for new adds).
    // Usually for 'add', we trust Firestore to make the ID.
    // But our toMap includes everything. Let's use the map but let Firestore handle ID if empty.
    
    await _firestore.collection('colleges').add(college.toMap());
  }

  /// Updates an existing college.
  /// Automatically updates the 'updatedAt' field.
  Future<void> updateCollege(College college) async {
    final data = college.toMap();
    data['updatedAt'] = FieldValue.serverTimestamp();
    
    await _firestore.collection('colleges').doc(college.id).update(data);
  }

  /// Toggles the 'isActive' status of a college.
  Future<void> toggleCollegeStatus(String id, bool isActive) async {
    await _firestore.collection('colleges').doc(id).update({
      'isActive': isActive,
      'updatedAt': FieldValue.serverTimestamp(),
    });
  }

  /// Soft deletes a college by setting 'isDeleted' to true.
  /// Also sets 'isActive' to false to be safe.
  Future<void> softDeleteCollege(String id) async {
    await _firestore.collection('colleges').doc(id).update({
      'isDeleted': true,
      'isActive': false,
      'updatedAt': FieldValue.serverTimestamp(),
    });
  }
}

final collegeRepositoryProvider = Provider<CollegeRepository>((ref) {
  final firebaseService = ref.watch(firebaseServiceProvider);
  return CollegeRepository(firebaseService.firestore);
});

final collegesStreamProvider = StreamProvider<List<College>>((ref) {
  final repository = ref.watch(collegeRepositoryProvider);
  return repository.getCollegesStream();
});
