import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../../../core/services/firebase_service.dart';
import '../../../orders/data/models/order_model.dart';
import '../models/payment_log_model.dart';

class FinanceRepository {
  final FirebaseFirestore _firestore;

  FinanceRepository(this._firestore);

  /// Streams all financial transactions
  Stream<List<PaymentLog>> getPaymentLogsStream() {
    return _firestore
        .collection('payments')
        .orderBy('createdAt', descending: true)
        .snapshots()
        .map((snapshot) =>
            snapshot.docs.map((doc) => PaymentLog.fromFirestore(doc)).toList());
  }

  /// Mark a payout as paid
  Future<void> markAsPaid(String id) async {
    await _firestore.collection('payments').doc(id).update({
      'status': PaymentStatus.paid.name,
      'paidAt': FieldValue.serverTimestamp(),
    });
  }

  /// Mark a payout as failed
  Future<void> markAsFailed(String id) async {
    await _firestore.collection('payments').doc(id).update({
      'status': PaymentStatus.failed.name,
    });
  }

  /// Create a new payment record (typically called by Cloud Functions or Order settlement logic)
  Future<void> createPaymentLog(PaymentLog log) async {
    await _firestore.collection('payments').add(log.toMap());
  }

  /// Automated settlement logic for an order
  Future<void> settleOrder(OrderModel order) async {
    // 1. Check if already settled
    final existing = await _firestore
        .collection('payments')
        .where('orderId', isEqualTo: order.id)
        .limit(1)
        .get();
    
    if (existing.docs.isNotEmpty) return;

    // 2. Calculate vendor share
    // Net = Total - Delivery (goes to rider) - Platform (goes to us)
    final netPayout = order.totalAmount - order.deliveryFee - order.platformFee;

    final log = PaymentLog(
      id: '', // Generated by Firestore
      orderId: order.id,
      vendorName: order.storeName,
      storeId: order.storeId,
      amount: order.totalAmount,
      platformCommission: order.platformFee,
      netPayout: netPayout,
      status: PaymentStatus.pending,
      createdAt: DateTime.now(),
    );

    await createPaymentLog(log);
  }
}

final financeRepositoryProvider = Provider<FinanceRepository>((ref) {
  final firebaseService = ref.watch(firebaseServiceProvider);
  return FinanceRepository(firebaseService.firestore);
});

final paymentLogsStreamProvider = StreamProvider<List<PaymentLog>>((ref) {
  final repository = ref.watch(financeRepositoryProvider);
  return repository.getPaymentLogsStream();
});
